//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyOpCodeTable.Shared.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyOpCodeTable.Shared.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Name&quot;: &quot;add&quot;,
        ///    &quot;Value&quot;: &quot;58&quot;,
        ///    &quot;Size&quot;: &quot;1&quot;,
        ///    &quot;Info&quot;: &quot;Adds two values and pushes the result onto the evaluation stack&quot;,
        ///    &quot;OpCodeType&quot;: &quot;Primitive&quot;,
        ///    &quot;FlowControl&quot;: &quot;Next&quot;,
        ///    &quot;OperandType&quot;: &quot;InlineNone&quot;,
        ///    &quot;StackBehaviourPush&quot;: &quot;Push1&quot;,
        ///    &quot;StackBehaviourPop&quot;: &quot;Pop1_pop1&quot;
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;add.ovf&quot;,
        ///    &quot;Value&quot;: &quot;d6&quot;,
        ///    &quot;Size&quot;: &quot;1&quot;,
        ///    &quot;Info&quot;: &quot;Adds two integers, performs an overflow check, and pushes the result onto the evaluation stack&quot;,
        ///    &quot;OpCodeTyp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OpCodes {
            get {
                return ResourceManager.GetString("OpCodes", resourceCulture);
            }
        }
    }
}
